### PR TITLE
corrected syntax error in 008 bash-arrays.md file 

### PR DESCRIPTION
**Pull request by vipul-2003**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [x] 📝 Documentation Update
- [ ] 🚩 Other

## Description

bug #66 has been corrected in .md file 

please mark it hacktoberfest2022 if you can  : )
thanks You ❤️

### CODE REVIEW

**Review by bobbyiliev — CHANGES_REQUESTED** [review]
Hi there,

Thanks for the PR. For me this does not seem to be working correctly, what version o BASH are you using?

```bash
my_array=("value 1" "value 2" "value 3" "value 4")
echo ${#my_array[@]}
# Output: 4
echo ${#my_array}
# Output: 7 
```

**Comment by vipul-2003** [comment]
My git bash version is older ... I think this might be due to older version 


I used to run the same command on online shell and results are same as yours .

**Comment by bobbyiliev** [comment]
> My git bash version is older ... I think this might be due to older version
> 
> I used to run the same command on online shell and results are same as yours .

Thank you for confirming that you are using an older version, I'll close this PR in this case, but also marked it as HF accepted as it was a valid suggestion.

**Comment by vipul-2003** [comment]
Thanks you @bobbyiliev for label 😁

**Pull request closed without merging**
