### PR TITLE
Translation of First Five chapters of this book in HINDI language fix issue #136 (changes-made)

### LINKED ISSUE #136: Hindi-Translation of the Book

### PR DESCRIPTION
**Pull request by soniyaprasad77**
## What type of PR is this? (check all applicable)
Fixes #136 
'This PR is the translation of the first five chapters of the book INTODUCTION TO BASH SCRIPTING in HINDI LANGUAGE

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [x] 🚩 Other

## Added to documentation?
Yes

- [ ] 📜 Tranlation of the book
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

### CODE REVIEW

**Review by bobbyiliev — CHANGES_REQUESTED** [review]
Thank you for this contribution! Would you mind renaming the files so that they keep the exact same naming convention as the other translations, eg:

image

**Comment by soniyaprasad77** [comment]
Sure

**Comment by soniyaprasad77** [comment]
@bobbyiliev Is it okay now?

**Review by bobbyiliev — CHANGES_REQUESTED** [review]
Thank you! 

Is it OK if we go ahead and delete the old files as well as they will not be picked up by the Ibis tool when the PDF is built:

image

**Comment by soniyaprasad77** [comment]
@bobbyiliev  changes are made successfully. Do checkOut!

**Review by bobbyiliev — APPROVED** [review]
Looks good! Thank you for your contribution!

**Pull request merged**
